### ISSUE TITLE
Говнище ненужное

### ISSUE THREAD

**Issue by forwork10** [SobakaBarabaka74/MK_String#3]
Во первых, код выглядит ужасно. Использование такого количества структур, перегрузок и тд - просто бессмыслено.
Во вторых - бесполезная хуета! Гораздо эффективнее будет сделать в какой либо структуре простой массив символов, ведь с++ это вовсе не интерпретируемый язык программирования и использовать такой бред - как минимум глупо)

**И ХВАТИТ УДАЛЯТЬ issue) что в тг, что здесь - ты пытаешься ограничить слово чтобы тебя просто не засрали) Какой же ты жалкий)**

**Comment by SobakaBarabaka74** [comment]
Lua говно кодер))
Разберём твой бред по частям
1. Что ужасно, ты долбаёб что ли), иди чекни свои говно lua скрипты :) 
2. ПЕРЕГРУЗКИ БЕССМЫСЛЕННАЯ ХУЕТа. А ты точно в себе?) тоесть ты хочешь сказать, что я буду писать допустим цикл чтобы сложить строки, вместо того чтобы написать 1 оператор?) пошёл в пизду. 
3. "Гораздо эффективней" Ну ты долбаёб! Я тебе 3 раз повторяю, это было сделано для практики, и твоего ненужного не компетентного мнения никто не спрашивал, и мнение lua говно кодера тут не нужно:)

**Comment by justqstn** [comment]
ты даже не видел эти луа скрипты, тебя уже рвет... малой угомонись

**Comment by forwork10** [comment]
> Lua говно кодер))
> Разберём твой бред по частям
> 1. Что ужасно, ты долбаёб что ли), иди чекни свои говно lua скрипты :) 
> 2. ПЕРЕГРУЗКИ БЕССМЫСЛЕННАЯ ХУЕТа. А ты точно в себе?) тоесть ты хочешь сказать, что я буду писать допустим цикл чтобы сложить строки, вместо того чтобы написать 1 оператор?) пошёл в пизду. 
> 3. "Гораздо эффективней" Ну ты долбаёб! Я тебе 3 раз повторяю, это было сделано для практики, и твоего ненужного не компетентного мнения никто не спрашивал, и мнение lua говно кодера тут не нужно:) 

да тебя рвёт уже :)
ты у нас сидишь и **С ТЕЛЕФОНЧИКА ПИШЕШЬ ГОВНО ХУЕТУ** и считаешь себя крутым умным гением - хотя ты уже доказал недавно какой ты крутой - написал что выучишь бнм и сделаешь читы, а через день **СЛИЛ КОХНО БНМ ЧТОБЫ ПОФИКСИЛ И ЛИВНУЛ С ИГРЫ**. Клоун просто... ты кстати вместо того чтобы себе ротик от говна подтереть **начал че то писать про мои коды луа** - хотя ты даже иэ
х не видел..
